#  NUmpy commands basics:

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [6]:
import pandas as pd
#working on numpy(numerical python)
import numpy as np
import matplotlib.pyplot as plt

In [7]:
# creating an array
a=np.array([(1,2,3,4),(4,5,6,7)])
a

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [8]:
#type of data is
type(a)

numpy.ndarray

In [9]:
#gives no of rows and columns in the array
a.shape

(2, 4)

In [11]:
#this command gives no of elements present in the array
a.size

8

In [15]:
#to reshape columns as rows and rows as columns
a=a.reshape(4,2)
a

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 7]])

In [18]:
#to find the index location of the ARRAY
a[0]

array([1, 2, 3, 4])

In [21]:
a[0,2]

3

In [25]:
a[1]

array([4, 5, 6, 7])

In [26]:
# to get the min value from the array
a.min()

1

In [27]:
#to get the maximum value from the array
a.max()

7

In [28]:
#to get sum of all the elements in the array
a.sum()

32

In [29]:
#axis = 0 makes the row wise operations
#axis = 1 makes column wise operations
a.sum(axis=0)

array([ 5,  7,  9, 11])

In [30]:
a.sum(axis=1)

array([10, 22])

#   duplicates


In [37]:
#creating data frame using pandas(must)
dup=pd.DataFrame({'col1':['A','A','B','B','B'],'col2':['2','2','2','3','3']})

In [38]:
#to open  the created file
dup

col1 col2
0    A    2
1    A    2
2    B    2
3    B    3
4    B    3

In [42]:
#to show the duplicated values as true
dup.duplicated()

0    False
1     True
2    False
3    False
4     True
dtype: bool

In [43]:
#to remove the duplicated values
dup.drop_duplicates()

col1 col2
0    A    2
2    B    2
3    B    3

In [50]:
# to show the duplicated values
dup[dup.duplicated()]

col1 col2
1    A    2
4    B    3

In [52]:
#to check the null values
dup.isnull().sum()

col1    0
col2    0
dtype: int64